guru:
  jms:
    failover: tcp://localhost:8161

#--- indica separacion de archivo (como si fuera otro archivo)
---
spring:
  profiles: DE # es como tener un archivo application-DE.yml

guru:
  jms:
    failover: tcp://fuhrer-host:8161